@echo off
echo Starting BEST sweeps for all datasets...
if not exist logs\ablations_tabular mkdir logs\ablations_tabular

set SCRIPT=run_ablations_tabular.py
set LOG_DIR=logs\ablations_tabular\best_runs

if not exist %LOG_DIR% mkdir %LOG_DIR%

echo [%time%] Running BEST_ADULT...
powershell -Command "python -u %SCRIPT% --dataset adult --sweep BEST_ADULT --baseline 2>&1 | Tee-Object -FilePath %LOG_DIR%\best_adult.log -Append"
if %errorlevel% neq 0 echo [WARNING] BEST_ADULT failed, continuing...

echo [%time%] Running BEST_CENSUS...
powershell -Command "python -u %SCRIPT% --dataset census --sweep BEST_CENSUS --baseline 2>&1 | Tee-Object -FilePath %LOG_DIR%\best_census.log -Append"
if %errorlevel% neq 0 echo [WARNING] BEST_CENSUS failed, continuing...

echo [%time%] Running BEST_CERVICAL...
powershell -Command "python -u %SCRIPT% --dataset cervical --sweep BEST_CERVICAL --baseline 2>&1 | Tee-Object -FilePath %LOG_DIR%\best_cervical.log -Append"
if %errorlevel% neq 0 echo [WARNING] BEST_CERVICAL failed, continuing...

echo [%time%] Running BEST_CREDIT...
powershell -Command "python -u %SCRIPT% --dataset credit --sweep BEST_CREDIT --baseline 2>&1 | Tee-Object -FilePath %LOG_DIR%\best_credit.log -Append"
if %errorlevel% neq 0 echo [WARNING] BEST_CREDIT failed, continuing...

echo [%time%] Running BEST_EPILEPTIC...
powershell -Command "python -u %SCRIPT% --dataset epileptic --sweep BEST_EPILEPTIC --baseline 2>&1 | Tee-Object -FilePath %LOG_DIR%\best_epileptic.log -Append"
if %errorlevel% neq 0 echo [WARNING] BEST_EPILEPTIC failed, continuing...

echo [%time%] Running BEST_ISOLET...
powershell -Command "python -u %SCRIPT% --dataset isolet --sweep BEST_ISOLET --baseline 2>&1 | Tee-Object -FilePath %LOG_DIR%\best_isolet.log -Append"
if %errorlevel% neq 0 echo [WARNING] BEST_ISOLET failed, continuing...

echo [%time%] Running BEST_COVTYPE...
powershell -Command "python -u %SCRIPT% --dataset covtype --sweep BEST_COVTYPE --baseline 2>&1 | Tee-Object -FilePath %LOG_DIR%\best_covtype.log -Append"
if %errorlevel% neq 0 echo [WARNING] BEST_COVTYPE failed, continuing...

echo [%time%] Running BEST_INTRUSION...
powershell -Command "python -u %SCRIPT% --dataset intrusion --sweep BEST_INTRUSION --baseline 2>&1 | Tee-Object -FilePath %LOG_DIR%\best_intrusion.log -Append"
if %errorlevel% neq 0 echo [WARNING] BEST_INTRUSION failed, continuing...

echo.
echo [%time%] All BEST sweeps complete.
echo Logs saved to %LOG_DIR%
pause